In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("datasets/final_risk_analysis_dataset.csv")

In [3]:
df_s = pd.read_csv("datasets/snythetic_risk_analysis_dataset.csv")

In [4]:
df_s.head(10)

,Customer_ID,County,Population_Density_Category,Annual_Income,Monthly_Inhand_Salary,Outstanding_Debt,Num_of_Loan,Total_EMI_per_month,Credit_Utilization_Ratio,Credit_History_Age,Num_of_Delayed_Payment,Monthly_Balance,Default_Flag
0,1,Bungoma,Medium,1.386561e+06,55475.700792,0.000000,7,8000.000000,0.505491,82,3,27770.389844,1
1,2,Nandi,Very High,1.058346e+06,57634.428877,153632.232660,0,6345.003956,0.800986,212,2,24532.681689,1
2,3,Kitui,High,9.503773e+05,97376.322957,237457.233956,0,8000.000000,0.508330,31,1,12957.594385,0
3,4,Homa Bay,High,1.015708e+06,81118.618201,294350.333127,2,8000.000000,0.245680,192,2,19694.288773,1
4,5,Wajir,Very High,6.442205e+05,98075.702463,238160.225981,2,8000.000000,0.667300,226,3,32406.462426,1
5,6,Murang'a,High,7.475578e+05,81392.256246,166335.588839,5,8000.000000,0.832819,198,2,35166.997666,1
6,7,Bungoma,Medium,8.163028e+05,66818.840705,463713.189071,3,8000.000000,0.360618,166,1,10054.222946,0
7,8,Nyeri,Medium,9.971056e+05,75647.717210,418496.929306,1,8000.000000,0.113960,39,1,21134.969759,0
8,9,Turkana,High,7.913119e+05,79021.973650,105140.222671,5,0.000000,0.873358,65,3,41947.373301,0
9,10,Isiolo,Medium,7.746404e+05,108204.168054,148924.384247,6,7947.013009,0.663997,129,1,16027.221988,1

In [5]:
df.head(10)

,Age,Annual_Income,Monthly_Inhand_Salary,Num_Bank_Accounts,Num_Credit_Card,Interest_Rate,Num_of_Loan,Delay_from_due_date,Num_of_Delayed_Payment,Changed_Credit_Limit,...,normalized_savings,normalized_utilization,normalized_utilization_risk,normalized_inquiry_intensity,normalized_investment_ratio,normalized_loan_burden_index,behavioral_risk_indicator,credit_mix_quality,normalized_savings_capacity_ratio,population_density_factor
0,28,34847.840,3037.986667,2,4,6,1,3,1,5.42,...,0.159691,1.0,1.0,1.000000,0.013058,1.0,0,2,0.980744,0.96
1,28,34847.840,3037.986667,2,4,6,1,3,3,5.42,...,0.099821,1.0,1.0,1.000000,0.082800,1.0,0,2,0.910979,1.04
2,55,30689.890,2612.490833,2,5,4,1,5,6,1.99,...,0.127396,1.0,1.0,0.666667,0.073421,1.0,0,2,0.920267,0.96
3,55,4148862.000,2612.490833,2,5,4,1,6,6,1.99,...,0.115133,1.0,1.0,1.000000,0.089510,1.0,0,2,0.904172,0.96
4,45,31370.800,2825.233333,1,6,12,2,2,3,5.76,...,0.133211,1.0,1.0,0.714286,0.038716,1.0,0,2,0.944770,0.96
5,36,54392.160,4766.680000,6,4,14,3,10,8,5.54,...,0.061397,1.0,1.0,1.000000,0.069122,1.0,1,1,0.904767,1.04
6,36,54392.160,4766.680000,6,4,14,3,10,10,5.54,...,0.102135,1.0,1.0,1.000000,0.030482,1.0,1,1,0.943415,0.96
7,39,8701.545,519.128750,6,5,32,7,23,10,8.86,...,0.514715,1.0,1.0,1.000000,0.072379,1.0,1,1,0.857079,1.08
8,37,25546.260,2415.855000,8,7,14,5,16,15,1.83,...,0.115525,1.0,1.0,0.875000,0.058361,1.0,1,1,0.899672,1.04
9,31,31993.780,2942.148333,6,6,7,2,8,14,6.28,...,0.147135,1.0,1.0,0.142857,0.029232,1.0,1,1,0.955415,1.04

In [6]:
df.shape

(8744, 34)

In [7]:
df_s.Default_Flag.value_counts()

Default_Flag
1    5839
0    4161
Name: count, dtype: int64

In [9]:
risk_score = (
    0.5*(df["Outstanding_Debt"] / df["Annual_Income"]) + 
    0.2*(df["Total_EMI_per_month"] / df["Monthly_Inhand_Salary"]) + 
    0.2*(df["Num_of_Delayed_Payment"]/5) + 
    0.1*(df["Credit_Utilization_Ratio"])
)

prob_default = 1/(1+np.exp(-(4*risk_score - 1.5)))

df["Default_Flag"] = np.random.binomial(1, prob_default)

df.Default_Flag.value_counts()

Default_Flag
1    8744
Name: count, dtype: int64

In [11]:
risk_score = (
    0.25*(df["Outstanding_Debt"] / df["Annual_Income"]) + 
    0.20*(df["Total_EMI_per_month"] / df["Monthly_Inhand_Salary"]) + 
    0.20*(df["Num_of_Delayed_Payment"] / df["Num_of_Loan"]) + 
    0.10*(df["Credit_Utilization_Ratio"] / 100) + 
    0.10*(df["Num_Credit_Inquiries"] / 10) + 
    0.10*(1 - df["Credit_History_Age"] / 120) + 
    0.05*(1 - df["Monthly_Balance"] / df["Monthly_Inhand_Salary"])
)

#risk_score_noise = risk_score + np.random.normal(0,0.03,len(df))

prob_default =  1/(1+np.exp(-(6*(risk_score-0.5))))

df["Default_Flag"] = np.random.binomial(1, prob_default)

df.Default_Flag.value_counts()

c:\Users\Admin\AppData\Local\Programs\Python\Python313\Lib\site-packages\pandas\core\arraylike.py:399: RuntimeWarning: overflow encountered in exp
  result = getattr(ufunc, method)(*inputs, **kwargs)

Default_Flag
1    6931
0    1813
Name: count, dtype: int64

In [12]:
risk_score.describe()

count    8.744000e+03
mean    -8.353790e+17
std      7.811575e+19
min     -7.304554e+21
25%      6.364057e-01
50%      8.759924e-01
75%      1.260444e+00
max      4.668325e+00
dtype: float64

In [14]:
risk_score = (
    0.22*(df["Outstanding_Debt"] / df["Annual_Income"]) +
    0.18*(df["Total_EMI_per_month"] / df["Monthly_Inhand_Salary"]) +
    0.18*(df["Num_of_Delayed_Payment"] / df["Num_of_Loan"]) +
    0.12*(df["Credit_Utilization_Ratio"] / 100) +
    0.10*(df["Num_Credit_Inquiries"] / 10) +
    0.10*(1 - df["Credit_History_Age"] / 120) +
    0.05*(df["Delay_from_due_date"]/30) +
    0.05*(1 - df["Monthly_Balance"] / df["Monthly_Inhand_Salary"])
)

center = risk_score.median()

prob_default = 1/(1+np.exp(-(4*(risk_score-center))))

df["Default_Flag"] = np.random.binomial(1, prob_default)

df.Default_Flag.value_counts(normalize=True)

c:\Users\Admin\AppData\Local\Programs\Python\Python313\Lib\site-packages\pandas\core\arraylike.py:399: RuntimeWarning: overflow encountered in exp
  result = getattr(ufunc, method)(*inputs, **kwargs)

Default_Flag
1    0.532937
0    0.467063
Name: proportion, dtype: float64

In [16]:
risk_score = (
    0.22*(df["Outstanding_Debt"] / df["Annual_Income"]) +
    0.18*(df["Total_EMI_per_month"] / df["Monthly_Inhand_Salary"]) +
    0.18*(df["Num_of_Delayed_Payment"] / df["Num_of_Loan"]) +
    0.12*(df["Credit_Utilization_Ratio"] / 100) +
    0.10*(df["Num_Credit_Inquiries"] / 10) +
    0.10*(1 - df["Credit_History_Age"] / 120) +
    0.05*(df["Delay_from_due_date"]/30) +
    0.05*(1 - df["Monthly_Balance"] / df["Monthly_Inhand_Salary"])
)
n_risk_score = risk_score + np.random.normal(0,0.015,len(df))

center = n_risk_score.quantile(0.65)

z = 4*(n_risk_score-center)

z = np.clip(z, -20, 20)

prob_default = 1/(1+np.exp(-z))

df["Default_Flag"] = np.random.binomial(1, prob_default)

df.Default_Flag.value_counts(normalize=True)

Default_Flag
0    0.571478
1    0.428522
Name: proportion, dtype: float64